In [1]:
import numpy as np

## The Basics

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [10]:
# Get dimension
print("a: {}".format(a.ndim))
print("b: {}".format(b.ndim))

a: 1
b: 2


In [11]:
# Get shape
b.shape

(2, 3)

In [12]:
# Get type
a.dtype

dtype('int64')

In [13]:
b.dtype

dtype('float64')

In [14]:
# Get item size
a.itemsize

8

In [15]:
# Get # elements
a.size

3

In [16]:
# Get total size
a.nbytes

24

In [17]:
b.itemsize

8

## Accessing/Changing specific elements, rows, columns, etc

In [4]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [5]:
# Get a specific element [r, c]
a[1, -2]

13

In [7]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [9]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [10]:
# Set an element
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [12]:
# Set a column
a[:, 2] = 5
print(a)

a[:, 2] = [50, 51]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2 50  4  5  6  7]
 [ 8  9 51 11 12 20 14]]


3D example

In [14]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
# working from the outside in...
# all of first dimension, 2nd element from 2nd dimension, all from 3rd dimension
b[:, 1, :] 

array([[3, 4],
       [7, 8]])

In [17]:
# set elements (must have the same shape)
b[:, 1, :] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [8]:
t = np.arange(9).reshape(3,3)
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
t[:, 0].max()

6

## Initializing Different Types of Arrays

In [11]:
# All 0's matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [16]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [23]:
# Fill a new array with the same shape as another
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

np.full_like(a, 4)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.88289431, 0.25001057],
       [0.30121219, 0.58438918],
       [0.01280873, 0.16321439],
       [0.87160112, 0.28142946]])

In [30]:
# Random Integer values
np.random.randint(1,11, size=(3,3)) # from 1-10

array([[8, 1, 4],
       [7, 6, 5],
       [9, 9, 1]])

In [31]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
# Repeat an array
arr = np.array([[1,2,3]])
np.repeat(arr, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Initialize Array Problem

Create this array....

    1 1 1 1 1
    1 0 0 0 1
    1 0 9 0 1
    1 0 0 0 1
    1 1 1 1 1

### My solution

In [39]:
s = np.ones((5,5), dtype='int32')
s

In [42]:
s[1:-1,1:-1] = 0
s

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [40]:
s

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [43]:
s[2,2] = 9
s

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

### Video solution

In [45]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
z = np.zeros((3,3))
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [48]:
output[1:-1, 1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Be careful when copying arrays!

Assignments are by reference by default!

In [51]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


Use the `.copy()` function if you need to create a new copy

In [52]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [50]:
a

array([100,   2,   3])

## Mathematics

[List of mathematical functions](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [63]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [56]:
a + 2

array([3, 4, 5, 6])

In [57]:
a * 3

array([ 3,  6,  9, 12])

In [64]:
a += 2
a

array([3, 4, 5, 6])

In [65]:
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [66]:
# exponent
a ** 2

array([ 1,  4,  9, 16])

In [67]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra
[Reference docs](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [72]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

# matrix multiply
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [73]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

###  Statistics

In [75]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
np.min(stats)

1

In [77]:
np.max(stats)

6

In [78]:
# largest from each row
np.max(stats, axis=1)

array([3, 6])

In [79]:
# largest row
np.max(stats, axis=0)

array([4, 5, 6])

In [80]:
np.sum(stats)

21

In [81]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [83]:
np.sum(stats, axis=1)

array([ 6, 15])

## Reorganizing Arrays

In [84]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
before.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [87]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [89]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load data from a file

In [99]:
# load data from text file
filedata = np.genfromtxt('data.txt', delimiter=',')

# convert to integer
filedata = filedata.astype('int32')

filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

### Boolean Masking and Advanced Indexing

In [95]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [96]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [97]:
# You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [101]:
# Check if any of the values in each column have a value greater than 50
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [102]:
# Check whether ALL of the values in each column have a value greater than 50
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [106]:
# Mask for all elements between 50 and 100
mask = ((filedata > 50) & (filedata < 100))
filedata[mask]

array([75, 75, 55, 78, 76, 88], dtype=int32)

In [107]:
# Mask for all elements NOT between 50 and 100
mask = ~((filedata > 50) & (filedata < 100))
filedata[mask]

array([  1,  13,  21,  11, 196,   4,   3,  34,   6,   7,   8,   0,   1,
         2,   3,   4,   5,   3,  42,  12,  33, 766,   4,   6,   4,   3,
         4,   5,   6,   7,   0,  11,  12,   1,  22,  33,  11, 999,  11,
         2,   1,   0,   1,   2,   9,   8,   7,   1], dtype=int32)

### Exercise

In [112]:
t = np.arange(1,31).reshape(6,5)
t

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [113]:
# extract a sub-matrix of 11, 12, 16, & 17
t[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [130]:
# extract a list of cells (provide a separate list for each dimension)
t[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [129]:
# Get the 4th & 5th elements from the first, 5th and 6th rows
t[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])