In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [10]:
# Get dimension
print("a: {}".format(a.ndim))
print("b: {}".format(b.ndim))

a: 1
b: 2


In [11]:
# Get shape
b.shape

(2, 3)

In [12]:
# Get type
a.dtype

dtype('int64')

In [13]:
b.dtype

dtype('float64')

In [14]:
# Get item size
a.itemsize

8

In [15]:
# Get # elements
a.size

3

In [16]:
# Get total size
a.nbytes

24

In [17]:
b.itemsize

8

## Accessing/Changing specific elements, rows, columns, etc

In [4]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [5]:
# Get a specific element [r, c]
a[1, -2]

13

In [7]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [9]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [10]:
# Set an element
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [12]:
# Set a column
a[:, 2] = 5
print(a)

a[:, 2] = [50, 51]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2 50  4  5  6  7]
 [ 8  9 51 11 12 20 14]]


3D example

In [14]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
# working from the outside in...
# all of first dimension, 2nd element from 2nd dimension, all from 3rd dimension
b[:, 1, :] 

array([[3, 4],
       [7, 8]])

In [17]:
# set elements (must have the same shape)
b[:, 1, :] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])